### PR TITLE
Write lesson on testing with Spring Data

### PR DESCRIPTION
**Pull request by kcleland0818**
This change is being made in the consumer canvas per the conversation on 7/22 to keep the same modules for Blackrock and AWS to streamline.

None of the original lessons covered testing with Spring Data, which is huge since it usually requires testing the persistence of data. I am just going to assume this may or may not play well with CodeGrade. But here is glimpse of how I used to write some of these integration tests with repositories. Let me know if you have any feedback as I would love to know if you guys have tested differently.

Also, I apologize for the length of these pull request. A good chunk of it is just setting up a Spring Data project. To make it possibly easier, I think you should be able to access this private repo I created with my code:

[Spring-Testing-Demo Project](https://github.com/kcleland0818/spring-testing-demo). If not, let me know.

### CODE REVIEW

**Comment by developerjaym** [comment]
At my old job, we tested a bit differently than this (I'm not sure if my old job's way had any advantages or disadvantages).

- We only unit-tested the service layer. This was because our controller methods typically did nothing except call a service method and because we had pretty thorough Postman/Karate tests. We didn't consider our repositories worthy of unit tests since the implementations were generated by Hibernate.
- Our service-layer tests mocked repositories just like any other dependency. We basically never fired up H2 like this, although one senior developer was fond of H2 databases for automated testing and local development.
- We never did MockMvc or SpringDataTest

**Review by developerjaym — APPROVED** [review]

**Review by linda-seiter — COMMENTED** [review]
Maybe briefly mention in the intro that "cat rescue" is a place, not an event.

Before the "Unit Testing and Spring Data" section, can you have them use Postman to add a Cat and a Rescue, then get them?  They just added lots of code (Cat and Rescue controller, service, repository) it would help to have a brief review of manual testing with postman so they see the endpoints and json structures.

Have them run the CatControllerUnitTest and RescueControllerUnitTest before starting the "Integration Testing and Spring Data" section?

Maybe show project structure for creating application-test.properties in test/resources

I might have missed this somewhere but I had to update pom.xml to add the H2 dependency

		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>

CatRepositoryIntegrationTest fails.  The test methods should be save() and findById()
(that took a while to figure out)

**Review by linda-seiter — COMMENTED** [review]
The instructions say to put CatRescueAcceptanceTest in the com.example.sprintestingdemo package but it is not clear they should just create the class in the test folder versus generate it from an existing class like the unit and integration tests.


Now that we have the order defined, let's go ahead and write the first test method, addRescue():
-this version of the code is missing the ObjectMapper import

So the first thing we changed was we noticed we use the ObjectMapper in both of our test methods thus far. Let's move that up to the setUp() method instead to instantiate.
- maybe move this above the code.  I originally copied the updated getRescue() thinking that was the only thing changing.

**Review by linda-seiter — APPROVED** [review]
**Acceptance testing** is ensures

- remove "is"

Looks great! Thanks for adding the postman manual tests.

**Comment by kcleland0818** [comment]
By the way, Silky, in the Postman tests, is a real cat up for adoption at the one shelter I volunteer at 

[Silky's Adoption Profile](https://happycatshaven.org/adoption/silky/)

**Review by developerjaym — APPROVED** [review]

**Review by linda-seiter — APPROVED** [review]

**Pull request merged**
